### ISSUE TITLE
Regression Trees

### ISSUE THREAD

**Issue by bensadeghi** [svs14/Orchestra.jl#1]
Hey Samuel,
Thanks so much for putting this together!!
I just recently added regression trees and random forests to the DecisionTree package (v0.3.1), so perhaps you could add them in to Orchestra as well. And please let me know if any issues come up.
Cheers

**Comment by svs14** [comment]
Hey Ben,

Glad to hear you like it! 
Thank you for the good code with DecisionTree.jl, working with it has been a breeze. :)

Right now I'm focusing on classification only, but will definitely be implementing regression throughout Orchestra in the future. When I do, I'll be sure to add your regression models.
I'll keep this issue open for now until this happens.

**Comment by bensadeghi** [comment]
Sounds good! Thanks
